### ISSUE TITLE
The filename, directory name, or volume label syntax is incorrect

### ISSUE THREAD

**Issue by goreacraft** [rojo-rbx/rbxlx-to-rojo#34]
Hi, i am trying to us it on a fairly big project that has a rbxlx file size of 48973KB and it fails each time with incomplete export. 
I run it with RUST_BACKTRACE=1 and i got this:

[2020-03-31T10:51:33Z INFO  rbxlx_to_rojo] rbxlx-to-rojo 0.1.0
[2020-03-31T10:51:33Z INFO  rbxlx_to_rojo] Select a place file.
[2020-03-31T10:51:42Z INFO  rbxlx_to_rojo] Opening place file
[2020-03-31T10:51:42Z INFO  rbxlx_to_rojo] Decoding place file, this is the longest part...
[2020-03-31T10:53:17Z INFO  rbxlx_to_rojo] Select the path to put your Rojo project in.
[2020-03-31T10:53:20Z INFO  rbxlx_to_rojo] Starting processing, please wait a bit...
thread 'main' panicked at 'can't write folder: Os { code: 123, kind: Other, message: "The filename, directory name, or volume label syntax is incorrect." }', src\libcore\result.rs:997:5
stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: <unknown>
  17: <unknown>
  18: <unknown>
  19: <unknown>
  20: <unknown>
  21: BaseThreadInitThunk
  22: RtlUserThreadStart

**Comment by goreacraft** [comment]
if i delete all folders from workspace and i am left with a file size of 4499KB it works, so it is something from my workspace that is breaking it (ir the file to big?)

**Comment by goreacraft** [comment]
i started deleting files from workshop and try again and i found something else that might be useful: "thread 'main' panicked at 'can't create file "Workspace\\Vendor\\Vendor Logs Palm \\init.meta.json": Os { code: 3, kind: NotFound, message: "The system cannot find the path specified." }', src\filesystem.rs:89:97"

**Comment by goreacraft** [comment]
i finally made it work, for some reason it does not like disabled scripts in workspace i think
